# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

inherit_from:
  - https://raw.githubusercontent.com/projectblacklight/arclight/refs/heads/main/.rubocop.yml

AllCops:
  Exclude:
    - "gems/**/*"
    - "db/**/*"
  TargetRubyVersion: 3.4.3

Style/StringLiterals:
  EnforcedStyle: single_quotes

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBrackets: no_space
