default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  primary: &primary_production
    <<: *default
    database: db/production.sqlite3
  cache:
    <<: *primary_production
    database: db/production_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: db/production_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: db/production_cable.sqlite3
    migrations_paths: db/cable_migrate
